name: coursemaster
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: node app.js
    source_dir: /
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        scope: RUN_TIME
        value: your_mongodb_uri_here
      - key: DB_NAME
        value: coursemaster_db